version: "2"

run:
  timeout: 3m
  tests: true

linters:
  default: standard
  enable:
    - bodyclose
    - errorlint
    - gosec
    - misspell
    - unconvert
    - unparam
    - whitespace

formatters:
  enable:
    - gofmt
    - goimports
